version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  all:
    docker:
      - image: cimg/node:22.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
            - v2-npm-deps-
      - node/install-packages
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm run prettier
      - run: npm run build
      - run: npm run test

workflows:
  danoni-editor:
    jobs:
      - all
